#![allow(dead_code)]
#![allow(unused_imports)]

[package]
name = "rusync"
version = "0.1.0"
authors = ["jiangplus <jiang.plus.times@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
rust-s3 = "0.22.12"
url = "2.1.1"
md5 = "0.7.0"
base16 = "0.2.1"
scan_dir = "0.3.3"
